// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjGONzA_O7AAee54WKz91TeLdahyxTcNs',
    appId: '1:202543511168:web:f4d8809a5c300dbe9c1865',
    messagingSenderId: '202543511168',
    projectId: 'eduhub-test',
    authDomain: 'eduhub-test.firebaseapp.com',
    storageBucket: 'eduhub-test.appspot.com',
    measurementId: 'G-DXZ3GCVFRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9MZXBJKW4cJ_Ibp3Wf0tJ1j7xq6NsXY',
    appId: '1:202543511168:android:9c7f3883e58552059c1865',
    messagingSenderId: '202543511168',
    projectId: 'eduhub-test',
    storageBucket: 'eduhub-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCGV7quNadrM-9MsDpGyyMygK9HY_FTM',
    appId: '1:202543511168:ios:8438e1f1bf29840f9c1865',
    messagingSenderId: '202543511168',
    projectId: 'eduhub-test',
    storageBucket: 'eduhub-test.appspot.com',
    iosBundleId: 'com.example.eduHub',
  );
}
