name: edu_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/LogoEduHub.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/LogoEduHub.png"
  remove_alpha_ios: true
  min_sdk_android: 21